# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages

services:
  - xvfb

after_failure:
- find tests/testsuite.dir -name testsuite.log -exec cat \{\} \;


branches:
  only:
    - master